sudo: required

services:
  - docker

before_install:
  - docker build -f Dockerfile -t gopkg .
  - docker run -d -p 8080:8080 
  - curl http://52.40.15.68/artifactory/gopkg/test/do-package-tree_linux -o /tmp/do-package-tree_linux -s
  - chmod +x /tmp/do-package-tree_linux

script:
  - /tmp/do-package-tree_linux |& tee $CIRCLE_TEST_REPORTS/gopkg_test.out
