sudo: required

language: go

go: 1.6.2

before_install:
  - go install github.com/djangoxv/gopkg
  - $HOME/gopath/bin/gopkg &
  - curl http://52.40.15.68/artifactory/gopkg/test/do-package-tree_linux -o /tmp/do-package-tree_linux -s
  - chmod +x /tmp/do-package-tree_linux

script:
  - /tmp/do-package-tree_linux
  - cat /tmp/gopkg.log
